# Generated by Django 2.2.1 on 2019-10-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('N', 'New Grads'), ('I', 'Internship')], default='N', max_length=1),
        ),
    ]
